services:
  - name: amitesh-portfolio
    buildCommand: npm install && npm run build
    staticPublishPath: build
    repo: https://github.com/amitesh786/Web-Portfolio
    type: static
    branch: main
